eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: ${EUREKA_SERVER_ADDRESS}
  instance:
    prefer-ip-address: true
    hostname: "${HOSTNAME}.eureka"