server:
  port: 8761
spring:
  application:
    name: EES-EUREKA-SERVER
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://localhost:8761/eureka #${EUREKA_SERVER_ADDRESS}
  instance:
    prefer-ip-address: true
    hostname: http://localhost #"${HOSTNAME}.eureka"

